
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: countries_api
    ports:
      - "8080:80"       
    environment:
      UseConnection: FromDockerToDockerConnection
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: countries_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: country_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
